### ISSUE TITLE
Add rultor, travis and 0pdd

### ISSUE THREAD

**Issue by amihaiemil** [decorators-squad/versioneye-api#2]
Configure the repo for these 3 services. Leave the rultor release scripts out, they are handled separately

**Comment by amihaiemil** [comment]
@SherifWaly Care to do this one? See how it's done in camel repository :D

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I would like to do this one :)

**Comment by amihaiemil** [comment]
@SherifWaly Thanks :)
