### ISSUE TITLE
Favorites.java:35-37: Provide RtFavorites implementation...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#20]
The puzzle `11-51606277` in [`src/main/java/com/amihaiemil/versioneye/Favorites.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/Favorites.java) (lines 35-37) has to be resolved: Provide RtFavorites implementation and unit tests. The class should work with a given request and username or simply fetch the authenticated user's favorites if no username is given.

The puzzle was created by amihaiemil on 18-Apr-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@SherifWaly Want to do this? I think it should be very similar to the way RtComments and RtComment are implemented. You can puzzle out the unit and integration testing :D

**Comment by amihaiemil** [comment]
@SherifWaly Here is how /favorites looks like (user ``datamd``):

```json
{
  "user": {
    "fullname": "datamd",
    "username": "datamd"
  },
  "favorites": [
    {
      "name": "doctrine/common",
      "language": "php",
      "prod_key": "doctrine/common",
      "version": "2.7.2",
      "prod_type": "composer"
    },
    {
      "name": "doctrine/doctrine-module",
      "language": "php",
      "prod_key": "doctrine/doctrine-module",
      "version": "2.0.0",
      "prod_type": "composer"
    },
    ...
  ],
  "paging": {
    "current_page": 1,
    "per_page": 30,
    "total_pages": 3,
    "total_entries": 70
  }
}
```

**Comment by amihaiemil** [comment]
And as I see, a project shows up as "favorite" if you follow it :)

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I would like to do it :D

**Comment by SherifWaly** [comment]
@amihaiemil What should happen if the page number isn't provided ? 
Also for the paging part I see that there is the same puzzle for Comments.

**Comment by amihaiemil** [comment]
@SherifWaly Well, for Comments it is mandatory to specify the page number (``Comments.fetch(int page)``). I imagine it should be the same for Favorites. If they have no clue what page to mention, I think it is intuitive that "1" should work :D And if they specify a negative number or whatever, it will crash most likely, but that's none of our business -- we are not supposed to pollute our code with validations for all sorts of user scenarios, I think.

**Comment by 0pdd** [comment]
The puzzle `11-51606277` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@SherifWaly thanks :)
