### ISSUE TITLE
Implement Organizations API

### ISSUE THREAD

**Issue by amihaiemil** [decorators-squad/versioneye-api#27]
Let's implement [Organizations](https://www.versioneye.com/api/#/organizations)

**Comment by amihaiemil** [comment]
@SherifWaly Would you like to do this? For starters, add the Oranizations and Oranization interfaces, as well as Projects and Teams. The Oranizations interface should offer methods for all the endpoints it exposes, as explained in the documentation.

Just these interfaces, the design should be covered in this ticket. Puzzle the rest out :D

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I want to do it :D

**Comment by amihaiemil** [comment]
@SherifWaly thank you :)
