### ISSUE TITLE
Solution to SSLHandshakeException

### ISSUE THREAD

**Issue by amihaiemil** [decorators-squad/versioneye-api#29]
When you run this the first time, java might not trust the SSL certificate from versioneye, so you need to add the public certificate that they offer into java's trust store: [this](http://stackoverflow.com/questions/6659360/how-to-solve-javax-net-ssl-sslhandshakeexception-error) is the solution (first comment)

**Comment by amihaiemil** [comment]
Let's add [TrustedWire](http://http.jcabi.com/pkix-validator.html) so we are sure this problem does not occur. But let's make it optional, ``VersionEye`` should have method ``trusted()`` which returns an instance of itself with the trusted wire.

**Comment by amihaiemil** [comment]
@SherifWaly Want to do this? When ``trusted()`` is called, you add the wire to the http request and return a new instance of the api with it :)

**Comment by amihaiemil** [comment]
@SherifWaly Of course, don't add the certificate to your trust store, so you can see if it works or not :D

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I would like to do it :)

**Comment by amihaiemil** [comment]
@SherifWaly Done here, thanks!
