### ISSUE TITLE
VersionEye.java:58-58: Add more tests to check that HTTP...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#31]
The puzzle `29-855dab61` in [`src/main/java/com/amihaiemil/versioneye/VersionEye.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/VersionEye.java) (lines 58-58) has to be resolved: Add more tests to check that HTTP reached server.

The puzzle was created by sherif on 19-Apr-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
Also, add a ``Troubleshooting`` section in README.md, pointing to the original issue, explaining what can be done if the SSL exception occurs...

**Comment by 0pdd** [comment]
The puzzle `29-855dab61` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
