### ISSUE TITLE
Comments.java:38-40: Provide a method to return a Paging,...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#33]
The puzzle `19-576c7749` in [`src/main/java/com/amihaiemil/versioneye/Comments.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/Comments.java) (lines 38-40) has to be resolved: Provide a method to return a Paging, which should offer information about the current page, number of pages etc. See src/test/resources/comments.json to see how paging looks like.

The puzzle was created by Mihai Emil Andronache on 21-Apr-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by SherifWaly** [comment]
@amihaiemil Can I do this one for Comments and Favorites :) ?

**Comment by amihaiemil** [comment]
@SherifWaly yes, you could introduce interface ``Paginated`` with method ``Paging paging()``? And I would make interfaces Comments and Favorites extend it. Or if you have a better idea, go with it :D

**Comment by SherifWaly** [comment]
@amihaiemil Ok, just sometimes I find classes named Rt and sometimes Json for Paging I think Json is more suitable or not :D ?

**Comment by amihaiemil** [comment]
@SherifWaly yes. Rt is for those that can make other http request to fetch more data, or return other objects which do that (they are not the final link in the chain). Json are those which simply have a json behind, it's the final json returned by the api after one or mre http calls :D

**Comment by 0pdd** [comment]
The puzzle `19-576c7749` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@SherifWaly thanks :)
