### ISSUE TITLE
Organizations.java:38-38: Provide RtOrganizations and unit...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#35]
The puzzle `27-9c31931b` in [`src/main/java/com/amihaiemil/versioneye/Organizations.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/Organizations.java) (lines 38-38) has to be resolved: Provide RtOrganizations and unit tests for it.

The puzzle was created by sherif on 23-Apr-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by SherifWaly** [comment]
@amihaiemil When I tried Organizations API as if I'm calling ``fetch`` method this is the output json file.
```json
[
  {
    "created_at": "2017-04-23T16:43:46.141Z",
    "updated_at": "2017-04-23T16:43:46.141Z",
    "name": "sherifwaly_orga",
    "company": null,
    "api_key": "88870f2710dba853a326"
  },
  {
    "created_at": "2017-04-24T19:42:59.560Z",
    "updated_at": "2017-04-24T19:42:59.599Z",
    "name": "sherif_test",
    "company": "",
    "api_key": "60dc805d094e3972eb1a"
  }
]
```
So I think it's a list of an object with 5 attributes but not the same as the ``Organization`` object, what do you think :) ?

**Comment by amihaiemil** [comment]
@SherifWaly true, Organization should also offer methods to access those attributes. An RtOrganization will have that json behind. For fluency and ease of use, an Organization also has methods for teams and projects.

**Comment by amihaiemil** [comment]
Also, Organization is the one to fetch its own teams and projects because that api_key is needed. So based on the encapsulated json's api_key, the two can be fetched :)

**Comment by amihaiemil** [comment]
@SherifWaly wanna do this? Start with RtOrganizations (this task) then Organization :D

**Comment by amihaiemil** [comment]
Not necesarily now in the weekend, next week (Im also away, wont be able to review)

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I would like to do it :)

**Comment by 0pdd** [comment]
The puzzle `27-9c31931b` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
