### ISSUE TITLE
Favorites.java:38-39: Provide integration and unit tests...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#40]
The puzzle `20-6a798f06` in [`src/main/java/com/amihaiemil/versioneye/Favorites.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/Favorites.java) (lines 38-39) has to be resolved: Provide integration and unit tests for RtFavorites and RtFavorite.

The puzzle was created by Mihai Emil Andronache on 27-Apr-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@SherifWaly want to do this? Look how it's done for comments. This task is inteesting since you can learn about the mkgrizzly container :)

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I would like to do it :D

**Comment by 0pdd** [comment]
The puzzle `20-6a798f06` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
