### ISSUE TITLE
RtOrganization.java:12-13: Implement, unit test this class and...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#45]
The puzzle `35-de23b30b` in [`src/main/java/com/amihaiemil/versioneye/RtOrganization.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/RtOrganization.java) (lines 12-13) has to be resolved: Implement, unit test this class and add methods for the organization attributes as (api_key).

The puzzle was created by sherif on 03-May-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `35-de23b30b` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@SherifWaly Thanks :)
