### ISSUE TITLE
RtOrganization.java:39-39: implement and test `projects()` method.

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#49]
The puzzle `37-8087fd76` in [`src/main/java/com/amihaiemil/versioneye/RtOrganization.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/RtOrganization.java) (lines 39-39) has to be resolved: implement and test `projects()` method.

The puzzle was created by amihaiemil on 04-May-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `37-8087fd76` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by SherifWaly** [comment]
@amihaiemil I think this issue should be closed now :)

**Comment by amihaiemil** [comment]
Right.. can you remove it? :D

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I will make a PR to remove the puzzle :D

**Comment by 0pdd** [comment]
The puzzle `37-8087fd76` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
