### ISSUE TITLE
Better paging mechanism

### ISSUE THREAD

**Issue by amihaiemil** [decorators-squad/versioneye-api#51]
We need a better, more object oriented paging mechanism. 
Currently we have ``Comments.fetch(int page): List<Comment>`` (which returns the Nth page of comments) and ``Comments.paging(): Paging`` which always returns data about the first page. This works, but will make the client's code very procedural. 

Instead, we should be having: ``Comments.fetch(): Page<Comment>``, where interface Page is an Iterable, with methods, hasNext and next among others.

**Comment by amihaiemil** [comment]
@SherifWaly I just realized we have better options for paging. Have a look here, do you understand what I'm saying? :D ``fetch()`` should return the first ``Page`` and a ``Page`` knows if there is a next page, knows how to return the next page, knows how many items are there in total etc.

**Comment by SherifWaly** [comment]
@amihaiemil So Page would have a ``List<Comment>`` ?

**Comment by amihaiemil** [comment]
@SherifWaly yes, or maybe not, maybe we make it even more elegant :D i'll think about it, do the Comments and you'll do favirites after that, ok? :D

**Comment by SherifWaly** [comment]
@amihaiemil Just I want to make sure about that it would be generic page ``Page<T>`` :D ?

**Comment by SherifWaly** [comment]
@amihaiemil Sorry I didn't understand you, I will wait until you do the Comments :D

**Comment by amihaiemil** [comment]
Yes, that would be nice, but I would like that when ``next()`` is called, the next page is fetched, so that means a Page<Comment> would have to instantiate objects of RtComment... and that seems kind of tricky, because Page will know only about interface Comment ... so we'll see about that too. But definetly, Page<T> would be nice

**Comment by SherifWaly** [comment]
@amihaiemil I could start it or you will think about it first :) ?

**Comment by amihaiemil** [comment]
@SherifWaly i'd like to look into it tomorrow if you don't mind :D so we clear things up. It's never ok to just start writing code without a clear solution

**Comment by SherifWaly** [comment]
@amihaiemil No problem I was just confused, sorry for that :D

**Comment by amihaiemil** [comment]
@SherifWaly no worries, dont apologize :p

**Comment by SherifWaly** [comment]
@amihaiemil ok :D

**Comment by amihaiemil** [comment]
@SherifWaly done :D you can have a look (I edited the README.md to show how the comments can be iterated over -- only the first page, or all the pages)
