### ISSUE TITLE
Favorites.java:39-40: Implement and unit-test FavoritesPage...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#53]
The puzzle `51-cac787c7` in [`src/main/java/com/amihaiemil/versioneye/Favorites.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/Favorites.java) (lines 39-40) has to be resolved: Implement and unit-test FavoritesPage (see how CommentsPage is done).

The puzzle was created by amihaiemil on 07-May-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@SherifWaly let me know if you want to do this one :D

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I want to do it, can I do it tonight as I'm working on another assignment now :D ?

**Comment by amihaiemil** [comment]
@SherifWaly whenever you have time is fine. Don't lose sleep over it :D

**Comment by 0pdd** [comment]
The puzzle `51-cac787c7` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@SherifWaly Thanks :)
