### ISSUE TITLE
MkVersionEye.java:39-40: Change ``post()`` method in ``Me`` by...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#60]
The puzzle `57-244db6f8` in [`src/main/java/com/amihaiemil/versioneye/MkVersionEye.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/MkVersionEye.java) (lines 39-40) has to be resolved: Change ``post()`` method in ``Me`` by passing a ``MkUser`` to the ``MkVersionEye`` ctor. (See #59 review)

The puzzle was created by sherif on 10-May-17. 

Estimate: 60 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@SherifWaly Did you understand what I explained about this? Want to do this? If you have other questions, feel free to asl :D

**Comment by SherifWaly** [comment]
@amihaiemil I didn't understand how I can use ``MkUser`` as it's different from the ``Authenticated`` user and how ``MkServer`` can hold multiple authenticated users :D ?

**Comment by amihaiemil** [comment]
@SherifWaly good questions. I'll explain a bit later when I get to a laptop :D

**Comment by amihaiemil** [comment]
@SherifWaly Right, so let's break this down into smaller tickets, it will be easier to understand :D

**Comment by SherifWaly** [comment]
@amihaiemil So you're going to close this one and open smaller tickets :D ?

**Comment by amihaiemil** [comment]
@SherifWaly well, not necesarily, we'll see how much we do in other tickets

**Comment by amihaiemil** [comment]
@SherifWaly I think everything was done here, right? :D we can know authenticate users with MkVersionEye without the need for a post method

**Comment by SherifWaly** [comment]
@amihaiemil yes, I wanted to ask you to close it but I found that 0pdd who opened it so the puzzle should be removed first :D

**Comment by 0pdd** [comment]
The puzzle `57-244db6f8` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
