### ISSUE TITLE
Implement MkJsonUser

### ISSUE THREAD

**Issue by amihaiemil** [decorators-squad/versioneye-api#61]
This class is needed for the mock version of the API.

``public final class MkJsonUser implements MkUser``

Interface MkUser contains the ``write`` methods for a user's attributes, like ``username(String), fullname(String)`` etc

In order to fit in the defined API, and also in order to have ``read`` methods, interface ``MkUser`` should extend interface ``Authenticated``.

It will be used like this:
```java
MkUser user = new MkJsonUser();
user = user.username("amihaiemil").fullname("Mihai A.");
VersionEye ve = new MkVersionEye(user); 

/*ctor MkVersionEye expects an Authenticated and since
MkUser extends Authenticated, it will be ok.*/
```

**Comment by amihaiemil** [comment]
@SherifWaly This is basically what MkUser will be and do :D does it make sense now?

**Comment by amihaiemil** [comment]
The write methods will return the instance of MkUser, for fluency, as you see in the description

**Comment by amihaiemil** [comment]
@SherifWaly or even better! instead of MkUser, say MkAuthenticated! That makes the most sense :D 
And MkJsonAuthenticated respectively

**Comment by SherifWaly** [comment]
@amihaiemil Yes, I understand it now. Thank you for explanation :D

**Comment by amihaiemil** [comment]
@SherifWaly done, thanks :)
