### ISSUE TITLE
MkServer should save more authenticated users

### ISSUE THREAD

**Issue by amihaiemil** [decorators-squad/versioneye-api#63]
Since more instances of ``MkVersionEye`` can be used with the same ``MkServer``, it should hold more authenticated users. At the same time, ``MkVersionEye`` should support both authenticated and unauthenticated ctors and retain the authenticated user's username, in order to fetch it from MkServer when needed.

**Comment by amihaiemil** [comment]
@SherifWaly Please wait for me to close this ticket: https://github.com/decorators-squad/versioneye-api/issues/64 before continuing here :D

**Comment by SherifWaly** [comment]
@amihaiemil I think the server should hold a jsonArray of authenticated users and search for the object that matches the username, let me know if I'm thinking right :D . Also I don't understand the unauthenticated users can you give an example for them please :D ?

**Comment by SherifWaly** [comment]
@amihaiemil I think it could be done like this better
```json
[
  "amihaiemil" : {.....},
  "SherifWaly" : {.....}
]
```
Also should I leave the Me API depend on the passed Authenticated or I would search by the username?

**Comment by amihaiemil** [comment]
@SherifWaly Well, the server would hold the authenticated users something like this:

```json
{
...
"authenticated": [
    {"amihaiemil":{...}},
    {"SherifWaly":{...}}
]
...
}
```

So yes, a JsonArray, attached to the key "authenticated", and this pair would be part the big Json. The whole server is a big big json.

The unauthenticated MkVersionEye will simply have a ctor without Authenticated, and the ``username`` will be empty. On the methods that require authenticated user (e.g. comments()), it will throw IllegalStateException or something, to point out that authentication is needed :D 

Do you see what I mean?

**Comment by amihaiemil** [comment]
@SherifWaly I also don't know the details right now, unless I start implementing. So, just do what you feel, and we'll see at review :) If you have other questions, ask away :P

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I will start :D

**Comment by amihaiemil** [comment]
@SherifWaly We're done here, thanks :)
