### ISSUE TITLE
MkVersionEye.java:46-49: Refactor implementation of MkMe so...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#68]
The puzzle `63-77eb9a24` in [`src/main/java/com/amihaiemil/versioneye/MkVersionEye.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/MkVersionEye.java) (lines 46-49) has to be resolved: "Refactor implementation of MkMe so that it uses the user's username rather that the Authenticated user. Pass Authenticated user to ``authenticate()`` method so that the authenticated user won't be retained."

The puzzle was created by sherif on 11-May-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `63-77eb9a24` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@SherifWaly done :D
