### ISSUE TITLE
Repository.java:35-36: Complete implementations and unit...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#88]
The puzzle `81-882850d7` in [`src/main/java/com/amihaiemil/versioneye/Repository.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/Repository.java) (lines 35-36) has to be resolved: "Complete implementations and unit tests for RtRepository."

The puzzle was created by sherif on 15-May-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by SherifWaly** [comment]
@amihaiemil Can I do this one :) ?

**Comment by amihaiemil** [comment]
@SherifWaly I'm not sure what was it about, but yes :D

**Comment by SherifWaly** [comment]
@amihaiemil RtRepository (from Github API) implementation wasn't done yet :D

**Comment by 0pdd** [comment]
The puzzle `81-882850d7` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@SherifWaly done here, thanks
