### ISSUE TITLE
Github.java:38-40: Complete Github API methods and move...

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#89]
The puzzle `81-7a3e2fdc` in [`src/main/java/com/amihaiemil/versioneye/Github.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/Github.java) (lines 38-40) has to be resolved: "Complete Github API methods and move fetch/paging to a repositories interface. You can also filter repositories by orga_name, prog. language, etc."

The puzzle was created by sherif on 15-May-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by SherifWaly** [comment]
@amihaiemil Can we use some setters for filters in Repositories that should be used before fetching :) ?

**Comment by amihaiemil** [comment]
@SherifWaly Yes, I think we will have a ``Search`` object, or something like that. To be used here and also when searching for products... and it will be something like this:

``versioneye.github().repositories().with(...).with(...).perform()``, same for products:
``versioneye.products().search().with(...).with(...).perform()``

But as usual, the image is not so clear right now. You can think about it and do something in that direction if you'd like :D

**Comment by amihaiemil** [comment]
@SherifWaly Or for course, ask any questions, maybe I get others idea as well

**Comment by SherifWaly** [comment]
@amihaiemil I was just thinking to do something like that 
``versioneye().github().repositories().lang("java").page(1).private(false).perform()`` 
and those methods would add query parameters to the request.

**Comment by amihaiemil** [comment]
@SherifWaly Beautiful solution, I would say. Go with it :P

**Comment by amihaiemil** [comment]
@SherifWaly But remember PDD, you don't have to do everything, just the outline is enough (this ticket here is rather big)

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I will do the Repositories and test it :)

**Comment by 0pdd** [comment]
The puzzle `81-7a3e2fdc` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@SherifWaly Done, thanks :)
