### ISSUE TITLE
RepositoriesPage.java:39-40: Write some unit tests for this class....

### ISSUE THREAD

**Issue by 0pdd** [decorators-squad/versioneye-api#91]
The puzzle `81-4d9fd085` in [`src/main/java/com/amihaiemil/versioneye/RepositoriesPage.java`](https://github.com/decorators-squad/versioneye-api/blob/master/src/main/java/com/amihaiemil/versioneye/RepositoriesPage.java) (lines 39-40) has to be resolved: "Write some unit tests for this class. They should be simmilar to those for CommentsPage."

The puzzle was created by Mihai Emil Andronache on 15-May-17. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by SherifWaly** [comment]
@amihaiemil Can I do this one :) ?

**Comment by amihaiemil** [comment]
@SherifWaly yes, sure

**Comment by 0pdd** [comment]
The puzzle `81-4d9fd085` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@SherifWaly Done here, thanks :)
